// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: pkg/core/proto/wwfsdb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Column represents a column in a table's schema.
type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IsNotNull     bool                   `protobuf:"varint,3,opt,name=is_not_null,json=isNotNull,proto3" json:"is_not_null,omitempty"`
	IsUnique      bool                   `protobuf:"varint,4,opt,name=is_unique,json=isUnique,proto3" json:"is_unique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{0}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Column) GetIsNotNull() bool {
	if x != nil {
		return x.IsNotNull
	}
	return false
}

func (x *Column) GetIsUnique() bool {
	if x != nil {
		return x.IsUnique
	}
	return false
}

// Schema represents the schema of a table.
type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*Column              `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{1}
}

func (x *Schema) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Row represents a single row of data in a table.
// The keys of the 'values' map are column names.
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]*anypb.Any  `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetValues() map[string]*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

// Page represents a single page of data, containing multiple rows.
type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Row                 `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{3}
}

func (x *Page) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Table represents a table in the database.
type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaCid     string                 `protobuf:"bytes,1,opt,name=schema_cid,json=schemaCid,proto3" json:"schema_cid,omitempty"`
	PageCids      []string               `protobuf:"bytes,2,rep,name=page_cids,json=pageCids,proto3" json:"page_cids,omitempty"`                                                         // CIDs of Page objects
	Indexes       map[string]string      `protobuf:"bytes,3,rep,name=indexes,proto3" json:"indexes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[column_name]index_cid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{4}
}

func (x *Table) GetSchemaCid() string {
	if x != nil {
		return x.SchemaCid
	}
	return ""
}

func (x *Table) GetPageCids() []string {
	if x != nil {
		return x.PageCids
	}
	return nil
}

func (x *Table) GetIndexes() map[string]string {
	if x != nil {
		return x.Indexes
	}
	return nil
}

// Database represents the entire database.
type Database struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tables         map[string]string      `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[table_name]table_cid
	OwnerPublicKey string                 `protobuf:"bytes,2,opt,name=owner_public_key,json=ownerPublicKey,proto3" json:"owner_public_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{5}
}

func (x *Database) GetTables() map[string]string {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *Database) GetOwnerPublicKey() string {
	if x != nil {
		return x.OwnerPublicKey
	}
	return ""
}

// IndexNode contains a list of CIDs for a given index key.
type IndexNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cids          []string               `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexNode) Reset() {
	*x = IndexNode{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexNode) ProtoMessage() {}

func (x *IndexNode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexNode.ProtoReflect.Descriptor instead.
func (*IndexNode) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{6}
}

func (x *IndexNode) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

// Index represents an index on a column.
// It maps a value (as a string) to a list of row CIDs.
type Index struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         map[string]*IndexNode  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{7}
}

func (x *Index) GetNodes() map[string]*IndexNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// RegistryEntry defines the structure for an entry in the registry.
type RegistryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbName        string                 `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	ProgramId     string                 `protobuf:"bytes,2,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"` // The IPNS Name (Key ID)
	KeyName       string                 `protobuf:"bytes,3,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`       // The local key name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryEntry) Reset() {
	*x = RegistryEntry{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryEntry) ProtoMessage() {}

func (x *RegistryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryEntry.ProtoReflect.Descriptor instead.
func (*RegistryEntry) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{8}
}

func (x *RegistryEntry) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *RegistryEntry) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *RegistryEntry) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

// ProllyNodeValues is a wrapper for a list of strings, used for leaf node values.
type ProllyNodeValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProllyNodeValues) Reset() {
	*x = ProllyNodeValues{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProllyNodeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProllyNodeValues) ProtoMessage() {}

func (x *ProllyNodeValues) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProllyNodeValues.ProtoReflect.Descriptor instead.
func (*ProllyNodeValues) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{9}
}

func (x *ProllyNodeValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// ProllyNode represents a node in an immutable B-tree (Prolly-Tree).
type ProllyNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values        []*ProllyNodeValues    `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`     // For leaf nodes
	Children      []string               `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"` // For internal nodes (CIDs)
	IsLeaf        bool                   `protobuf:"varint,4,opt,name=is_leaf,json=isLeaf,proto3" json:"is_leaf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProllyNode) Reset() {
	*x = ProllyNode{}
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProllyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProllyNode) ProtoMessage() {}

func (x *ProllyNode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_core_proto_wwfsdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProllyNode.ProtoReflect.Descriptor instead.
func (*ProllyNode) Descriptor() ([]byte, []int) {
	return file_pkg_core_proto_wwfsdb_proto_rawDescGZIP(), []int{10}
}

func (x *ProllyNode) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ProllyNode) GetValues() []*ProllyNodeValues {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ProllyNode) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ProllyNode) GetIsLeaf() bool {
	if x != nil {
		return x.IsLeaf
	}
	return false
}

var File_pkg_core_proto_wwfsdb_proto protoreflect.FileDescriptor

const file_pkg_core_proto_wwfsdb_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/core/proto/wwfsdb.proto\x12\x05proto\x1a\x19google/protobuf/any.proto\"m\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\vis_not_null\x18\x03 \x01(\bR\tisNotNull\x12\x1b\n" +
	"\tis_unique\x18\x04 \x01(\bR\bisUnique\"1\n" +
	"\x06Schema\x12'\n" +
	"\acolumns\x18\x01 \x03(\v2\r.proto.ColumnR\acolumns\"\x86\x01\n" +
	"\x03Row\x12.\n" +
	"\x06values\x18\x01 \x03(\v2\x16.proto.Row.ValuesEntryR\x06values\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"&\n" +
	"\x04Page\x12\x1e\n" +
	"\x04rows\x18\x01 \x03(\v2\n" +
	".proto.RowR\x04rows\"\xb4\x01\n" +
	"\x05Table\x12\x1d\n" +
	"\n" +
	"schema_cid\x18\x01 \x01(\tR\tschemaCid\x12\x1b\n" +
	"\tpage_cids\x18\x02 \x03(\tR\bpageCids\x123\n" +
	"\aindexes\x18\x03 \x03(\v2\x19.proto.Table.IndexesEntryR\aindexes\x1a:\n" +
	"\fIndexesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\bDatabase\x123\n" +
	"\x06tables\x18\x01 \x03(\v2\x1b.proto.Database.TablesEntryR\x06tables\x12(\n" +
	"\x10owner_public_key\x18\x02 \x01(\tR\x0eownerPublicKey\x1a9\n" +
	"\vTablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1f\n" +
	"\tIndexNode\x12\x12\n" +
	"\x04cids\x18\x01 \x03(\tR\x04cids\"\x82\x01\n" +
	"\x05Index\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.proto.Index.NodesEntryR\x05nodes\x1aJ\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.proto.IndexNodeR\x05value:\x028\x01\"b\n" +
	"\rRegistryEntry\x12\x17\n" +
	"\adb_name\x18\x01 \x01(\tR\x06dbName\x12\x1d\n" +
	"\n" +
	"program_id\x18\x02 \x01(\tR\tprogramId\x12\x19\n" +
	"\bkey_name\x18\x03 \x01(\tR\akeyName\"*\n" +
	"\x10ProllyNodeValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x86\x01\n" +
	"\n" +
	"ProllyNode\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12/\n" +
	"\x06values\x18\x02 \x03(\v2\x17.proto.ProllyNodeValuesR\x06values\x12\x1a\n" +
	"\bchildren\x18\x03 \x03(\tR\bchildren\x12\x17\n" +
	"\ais_leaf\x18\x04 \x01(\bR\x06isLeafB,Z*github.com/nnlgsakib/wwfsdb/pkg/core/protob\x06proto3"

var (
	file_pkg_core_proto_wwfsdb_proto_rawDescOnce sync.Once
	file_pkg_core_proto_wwfsdb_proto_rawDescData []byte
)

func file_pkg_core_proto_wwfsdb_proto_rawDescGZIP() []byte {
	file_pkg_core_proto_wwfsdb_proto_rawDescOnce.Do(func() {
		file_pkg_core_proto_wwfsdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_core_proto_wwfsdb_proto_rawDesc), len(file_pkg_core_proto_wwfsdb_proto_rawDesc)))
	})
	return file_pkg_core_proto_wwfsdb_proto_rawDescData
}

var file_pkg_core_proto_wwfsdb_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_core_proto_wwfsdb_proto_goTypes = []any{
	(*Column)(nil),           // 0: proto.Column
	(*Schema)(nil),           // 1: proto.Schema
	(*Row)(nil),              // 2: proto.Row
	(*Page)(nil),             // 3: proto.Page
	(*Table)(nil),            // 4: proto.Table
	(*Database)(nil),         // 5: proto.Database
	(*IndexNode)(nil),        // 6: proto.IndexNode
	(*Index)(nil),            // 7: proto.Index
	(*RegistryEntry)(nil),    // 8: proto.RegistryEntry
	(*ProllyNodeValues)(nil), // 9: proto.ProllyNodeValues
	(*ProllyNode)(nil),       // 10: proto.ProllyNode
	nil,                      // 11: proto.Row.ValuesEntry
	nil,                      // 12: proto.Table.IndexesEntry
	nil,                      // 13: proto.Database.TablesEntry
	nil,                      // 14: proto.Index.NodesEntry
	(*anypb.Any)(nil),        // 15: google.protobuf.Any
}
var file_pkg_core_proto_wwfsdb_proto_depIdxs = []int32{
	0,  // 0: proto.Schema.columns:type_name -> proto.Column
	11, // 1: proto.Row.values:type_name -> proto.Row.ValuesEntry
	2,  // 2: proto.Page.rows:type_name -> proto.Row
	12, // 3: proto.Table.indexes:type_name -> proto.Table.IndexesEntry
	13, // 4: proto.Database.tables:type_name -> proto.Database.TablesEntry
	14, // 5: proto.Index.nodes:type_name -> proto.Index.NodesEntry
	9,  // 6: proto.ProllyNode.values:type_name -> proto.ProllyNodeValues
	15, // 7: proto.Row.ValuesEntry.value:type_name -> google.protobuf.Any
	6,  // 8: proto.Index.NodesEntry.value:type_name -> proto.IndexNode
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_core_proto_wwfsdb_proto_init() }
func file_pkg_core_proto_wwfsdb_proto_init() {
	if File_pkg_core_proto_wwfsdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_core_proto_wwfsdb_proto_rawDesc), len(file_pkg_core_proto_wwfsdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_core_proto_wwfsdb_proto_goTypes,
		DependencyIndexes: file_pkg_core_proto_wwfsdb_proto_depIdxs,
		MessageInfos:      file_pkg_core_proto_wwfsdb_proto_msgTypes,
	}.Build()
	File_pkg_core_proto_wwfsdb_proto = out.File
	file_pkg_core_proto_wwfsdb_proto_goTypes = nil
	file_pkg_core_proto_wwfsdb_proto_depIdxs = nil
}
